Function to detect Participant analysis failure and abort the Group analysis
big-data-lab-team/mapreduce pull request #55
Opened 2017-10-01 22:02 UTC by tushargupta98

I have added function which detect failure in a participant analysis and aborts the group analysis with an error message.

2017-10-01 23:29 UTC, glatard requested changes
Great start! See (minor) comment.

2017-10-01 23:29 UTC, glatard commented on sim/SparkBIDS.py
> +            print("Error# Participant analysis failed. Aborting group analysis")
you can print this message in the previous if block (line 48). Then you don't need `self.participant_analysis_failed`. Print the message only if `self.do_group_analysis`.

2017-10-03 20:39 UTC, glatard commented
Also, the PR has to be done against the `develop` branch, not `master`.

2017-10-03 20:52 UTC, tushargupta98 commented
Sure Professor,
I will create a new PR for Develop branch and cancel the old one, if
possible.
For the previous comment, when I was making the change I wasn't sure as how
many times the error can occur, I mean to say whether it will happen just
once for each participant or if there is a different mechanism. Also, I
thought of consolidating the failure for both the participants into the
one  error message.

I will make the necessary change in the develop branch and create a new PR.

Thanks and Regards,
Tushar

On 3 October 2017 at 16:39, Tristan Glatard <notifications@github.com>
wrote:

> Also, the PR has to be done against the develop branch, not master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/big-data-lab-team/sim/pull/55#issuecomment-333971359>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ANeX4GoGt2Ap28a4fDLlL9fStbTTnr-Hks5sopuXgaJpZM4PqDJU>
> .
>

2017-10-06 22:19 UTC, closed without merging