add multiple reads function with memory parameter
big-data-lab-team/mapreduce pull request #8
Opened 2017-05-29 02:33 UTC by YongpingGao

add a function called reconstruct_mreads with memory parameter.

To reduce reload times, once the block is loaded, we can get more slices instead of just one slice.

However, the original multiple-reads (get one slice once loaded) can be achieved by setting mem < one big slice bytes(like mem = 0.01G, etc.)

2017-05-29 14:11 UTC, glatard requested changes
Nice work! See my comments in the review.

2017-05-29 14:11 UTC, glatard commented on python/imageutils.py
> +            block_shape = nib.load(legend.readline().strip()).header.get_data_shape()
the lines above should probably be put in a separate function, reused in different reconstruction methods.

2017-05-29 14:11 UTC, glatard commented on python/imageutils.py
> +                pass;
fine, but perhaps a bit convoluted?

2017-05-29 14:11 UTC, glatard commented on python/imageutils.py
> +            # n is blocks quatity in each axis. Assume all the blocks in the same size and are all cubic.
that doesn't work for BigBrain.

2017-05-29 14:11 UTC, glatard commented on python/imageutils.py
> +            n = (i + 1) ** (1.0 / 3)
give more meaningful name or explain what the variables will be used for: `X_size` vs `x_size`, `n`, `n_obs`.

2017-05-29 14:11 UTC, glatard commented on python/imageutils.py
> +        n_slices = int((mem / mem_s) // n_obs)
not sure why you divide by `n_obs` here.

2017-05-29 14:11 UTC, glatard commented on python/imageutils.py
> +                reconstructed.write(bytes_arr)
why isn't the header written in other reconstruction methods as well?

2017-05-29 14:11 UTC, glatard commented on python/imageutils.py
> +                    reconstructed.seek(postion, 0)
you should be able to seek only once every `n_slices` while now you seek much more than that. Also, that part of the code would deserve a little bit more of comments, or better named variables to understand what's going on.

2017-05-29 14:11 UTC, glatard commented on python/imageutils.py
> +                            block_data_arr = block_data[:, :, i: (i + n_slices if i + n_slices <= x_size else x_size)]
Do we know if nibabel loads have an overhead compared to native ones? In any case, let's keep them consistent all over the code (which I think they are), to allow for meaningful comparisons.

2017-05-29 14:11 UTC, glatard commented on python/rec_multi_reads.py
> +# info of header. Code should be modified before merging to imageutils.py
yes indeed :)

2017-05-29 14:11 UTC, glatard commented on python/rec_multi_reads.py
> +        n = 5
this can't be hardcoded.

2017-05-29 14:11 UTC, glatard commented on python/rec_multi_reads.py
> +def reconstruct_multi_reads(legend, img_shape, blocks_dir, out_image):
I'm assuming this method shouldn't have been pushed here, right?

2017-05-29 14:11 UTC, glatard commented on python/rec_multi_reads.py
> +    reconstruct_multi_reads("/data/bigbrain_blocks2/legend.txt", [3850, 3025, 3500], "/data/bigbrain_blocks2", "./recon_mreads.nii")
oops, no hard-coded path, pls.

2017-05-29 18:34 UTC, YongpingGao commented on python/imageutils.py
> +            block_shape = nib.load(legend.readline().strip()).header.get_data_shape()
Sure, I will fix it.

2017-05-29 18:34 UTC, YongpingGao commented on python/imageutils.py
> +                pass;
these lines is just to calculate how many blocks per axis. If not work for Bigbrain, I will figure out another way

2017-05-29 18:34 UTC, YongpingGao commented on python/imageutils.py
> +            # n is blocks quatity in each axis. Assume all the blocks in the same size and are all cubic.
these lines is just to calculate how many blocks per axis. If not work for Bigbrain, I will figure out another way

2017-05-29 18:34 UTC, YongpingGao commented on python/imageutils.py
> +            n = (i + 1) ** (1.0 / 3)
OK, I will add more comments.

2017-05-29 18:34 UTC, YongpingGao commented on python/imageutils.py
> +        n_slices = int((mem / mem_s) // n_obs)
I will add more comments on this.

2017-05-29 18:34 UTC, YongpingGao commented on python/imageutils.py
> +                reconstructed.write(bytes_arr)
I just copy the origin header in bytes and write it to the new image file. I am wondering if there is another way to create the header correctly.

2017-05-29 18:34 UTC, YongpingGao commented on python/imageutils.py
> +                            block_data_arr = block_data[:, :, i: (i + n_slices if i + n_slices <= x_size else x_size)]
Could you be more specific to this one? Do you mean I should use the function "load_image" in imageutils.py to load the image? if it is, I will fix that.

2017-05-29 18:34 UTC, YongpingGao commented on python/imageutils.py
> +                    reconstructed.seek(postion, 0)
Ok I will add more comments.

2017-05-29 18:34 UTC, YongpingGao commented on python/rec_multi_reads.py
> +# info of header. Code should be modified before merging to imageutils.py
rec_multi_reads.py should be removed as it's in the imageutls.py now and I forgot to do that, sry.

2017-05-29 18:34 UTC, YongpingGao commented on python/rec_multi_reads.py
> +def reconstruct_multi_reads(legend, img_shape, blocks_dir, out_image):
same reason, rec_multi_reads.py should be removed

2017-05-29 18:34 UTC, YongpingGao commented on python/rec_multi_reads.py
> +        n = 5
same reason, rec_multi_reads.py should be removed

2017-05-29 18:34 UTC, YongpingGao commented on python/rec_multi_reads.py
> +    reconstruct_multi_reads("/data/bigbrain_blocks2/legend.txt", [3850, 3025, 3500], "/data/bigbrain_blocks2", "./recon_mreads.nii")
same reason, rec_multi_reads.py should be removed

2017-05-29 18:35 UTC, YongpingGao commented
I have added some replies and I will fix them ASAP

2017-05-29 18:36 UTC, glatard commented on python/imageutils.py
> +            # n is blocks quatity in each axis. Assume all the blocks in the same size and are all cubic.
I mean, BigBrain blocks are not cubic, will that crash your code?

2017-05-29 18:37 UTC, glatard commented on python/imageutils.py
> +                reconstructed.write(bytes_arr)
It looks good, but I'm wondering why the header is not written in the other reconstruction  methods in the class. See @ValHayot's comment in Slack.

2017-05-29 18:41 UTC, glatard commented on python/imageutils.py
> +                            block_data_arr = block_data[:, :, i: (i + n_slices if i + n_slices <= x_size else x_size)]
Leave it like this but just note for later that nibabel might introduce an overhead in reading, and that when we compare different methods they should all use nibabel (or none of them should).

2017-05-30 02:07 UTC, YongpingGao commented
I have updated the code, let me know if there is more fix needed

2017-05-30 14:25 UTC, glatard requested changes
Comments are now perfect, but I think we should revise the logic in mreads.

2017-05-30 14:25 UTC, glatard commented on python/imageutils.py
> +            n_slices = 1
Well we should be able to write partial slices if the memory is too low.

2017-05-30 14:25 UTC, glatard commented on python/imageutils.py
> +        # 0 means memory the user set is too low which is smaller than one complete slice (mem_s * ny * nz)
Great comments, now it is crystal-clear!

2017-05-30 14:25 UTC, glatard commented on python/imageutils.py
> +        n_slices = int((mem / (mem_s * ny * nz)))
how about `n_slices = mem / (Y_size * Z_size * bytes_per_voxel)?

2017-05-30 14:25 UTC, glatard commented on python/imageutils.py
> +        for l, x in enumerate(range(0, X_size, x_size)):
so if the blocks have different x sizes, this will not work.

2017-05-30 14:25 UTC, glatard commented on python/imageutils.py
> +            for l2, i in enumerate(range(0, x_size, n_slices)):
pretty complicated...

2017-05-30 14:25 UTC, glatard commented on python/imageutils.py
> +                print("l2: {}, Remeaining memory: {} bytes".format(l2, mem - np_arr_yz.nbytes))
I'm not sure if it's correct. I think we can make this all clearer.

2017-06-05 02:26 UTC, YongpingGao commented
All cluster reads code are belong to Valerie, I copy the code from consider so that I can work based on her code.
This PR is just for your comments, please accept Valerie's PR first, then I will make my PR again.

2017-06-05 13:39 UTC, glatard commented
Unsurprisingly, this PR conflicts with master, now that #9 has been merged. @YongpingGao, could you resolve the conflict?

2017-06-05 21:13 UTC, YongpingGao commented
I just fix all the conflicts.

2017-06-06 00:55 UTC, glatard approved these changes
Excellent work!

2017-06-06 00:55 UTC, glatard commented on python/imageutils.py
> +            next_write_range = (next_write_range[0] + mem, next_write_range[1] + mem)
Shouldn't it be `next_write_range[0]+mem+1`?

2017-06-06 00:55 UTC, merged